package internal

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const hookScript = `#!/bin/sh                                                                                                                                
    # envsafe pre-commit hook                                                                                                                                    
    # Generated by envsafe                                                                                                                                       
                                                                                                                                                                 
    if command -v envsafe >/dev/null 2>&1; then                                                                                                                  
        envsafe hook verify                                                                                                                                      
    else                                                                                                                                                         
        if [ -f "main.go" ]; then                                                                                                                                
            go run . hook verify                                                                                                                                 
        else                                                                                                                                                     
            echo "⚠️  [envsafe] 'envsafe' command not found in PATH. Skipping hook checks."                                                                      
        fi                                                                                                                                                       
    fi                                                                                                                                                           
    `

func InstallHook() error {
	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		return fmt.Errorf("not a git repository (no .git folder found)")
	}

	hooksDir := filepath.Join(".git", "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")

	if _, err := os.Stat(hookPath); err == nil {
		content, readErr := os.ReadFile(hookPath)
		if readErr == nil && strings.Contains(string(content), "envsafe") {
			fmt.Println(Green("✅ envsafe pre-commit hook is already installed!"))
			return nil
		}
		return fmt.Errorf("a pre-commit hook already exists at %s. Please merge it manually or remove it to install envsafe", hookPath)
	}

	err := os.WriteFile(hookPath, []byte(hookScript), 0755)
	if err != nil {
		return fmt.Errorf("failed to write hook file: %w", err)
	}

	fmt.Println(Green("🚀 Pre-commit hook successfully installed!"))
	return nil
}

func UninstallHook() error {
	hookPath := filepath.Join(".git", "hooks", "pre-commit")

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Println(Yellow("ℹ️  No pre-commit hook found to uninstall."))
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err == nil && !strings.Contains(string(content), "envsafe") {
		return fmt.Errorf("the pre-commit hook at %s was not generated by envsafe. Please remove it manually", hookPath)
	}

	err = os.Remove(hookPath)
	if err != nil {
		return fmt.Errorf("failed to remove hook: %w", err)
	}

	fmt.Println(Green("🗑️  Pre-commit hook successfully uninstalled."))
	return nil
}

func VerifyCommit() error {
	cmd := exec.Command("git", "diff", "--cached", "--name-only")
	outputBytes, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("failed to run git diff: %w", err)
	}

	stagedFiles := strings.Split(string(outputBytes), "\n")
	var blockedFiles []string

	for _, file := range stagedFiles {
		file = strings.TrimSpace(file)
		if file == "" {
			continue
		}

		filename := filepath.Base(file)
		if strings.HasPrefix(filename, ".env") &&
			!strings.HasSuffix(filename, ".enc") &&
			!strings.HasSuffix(filename, ".example") {
			blockedFiles = append(blockedFiles, file)
		}
	}

	if len(blockedFiles) > 0 {
		fmt.Printf("❌ %s: You are attempting to commit unencrypted environment files:\n",
			Bold(Red("[envsafe] SECURITY WARNING")),
		)
		for _, file := range blockedFiles {
			fmt.Printf("   - %s\n", Red(file))
		}
		fmt.Println("\nActions required:")
		fmt.Printf("  1. Unstage these files: %s\n", Bold("git restore --staged <file>"))
		fmt.Printf("  2. Make sure they are added to your %s file.\n", Bold(".gitignore"))
		fmt.Printf("  3. Encrypt them using: %s\n", Bold("envsafe encrypt <file>"))
		return fmt.Errorf("commit blocked for security reasons")
	}

	infoEnv, err1 := os.Stat(".env")
	infoEnc, err2 := os.Stat(".env.enc")
	if err1 == nil && err2 == nil {
		if infoEnv.ModTime().After(infoEnc.ModTime()) {
			fmt.Printf("⚠️  %s: .env has been modified since .env.enc was last updated.\n",
				Bold(Yellow("[envsafe]")),
			)
			fmt.Printf("   Remember to run '%s' if you changed secrets!\n", Bold("envsafe encrypt"))
		}
	}

	if _, err := os.Stat(".env"); err == nil {
		ignoreCmd := exec.Command("git", "check-ignore", "-q", ".env")
		if ignoreErr := ignoreCmd.Run(); ignoreErr != nil {
			fmt.Printf("⚠️  %s: .env is NOT ignored by git! Please add it to your .gitignore.\n",
				Bold(Yellow("[envsafe]")),
			)
		}
	}

	return nil
}
